# Generated by Django 5.2.15 on 2026-06-30 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienciaAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_evento', models.CharField(choices=[('AUD', 'Audiencia Judicial'), ('LAPS', 'Lapso Procesal'), ('VENC', 'Vencimiento Contrato'), ('REC', 'Recordatorio General')], max_length=4)),
                ('fecha_hora', models.DateTimeField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('notificado_30', models.BooleanField(default=False)),
                ('notificado_60', models.BooleanField(default=False)),
                ('notificado_90', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audiencias_agenda',
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('DOC', 'Docente'), ('ADM', 'Administrativo'), ('OBR', 'Obrero')], max_length=3)),
                ('tipo', models.CharField(choices=[('FIJ', 'Fijo / Carrera'), ('CON', 'Contratado'), ('CAR', 'Libre Nombramiento y Remoción')], max_length=3)),
                ('marco_legal', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cargos',
                'ordering': ['categoria', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_expediente', models.CharField(max_length=50, unique=True)),
                ('numero_expediente_relativo', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_apellido', models.CharField(max_length=200, verbose_name='Nombre y Apellido')),
                ('cedula', models.CharField(max_length=20, verbose_name='Cédula')),
                ('tipo_modulo', models.CharField(choices=[('DESP', 'Calificación de Despido / Recientes'), ('INSP', 'Casos de Inspectoría / Horas Extra / Reclamos'), ('OFIC', 'Expedientes en Oficina Consultoría Jurídica'), ('CONT', 'Contrataciones y Convenios de la Universidad'), ('LITI', 'Litigios Judiciales y Administrativos'), ('SUST', 'Sustanciación de Procedimientos Disciplinarios'), ('IND', 'Índices de Inspectoría del Trabajo')], max_length=4)),
                ('estatus', models.CharField(blank=True, choices=[('RECIBIDO', 'Recibido'), ('EN_ANALISIS', 'En Análisis'), ('FIRMA', 'En Firma'), ('DESPACHADO', 'Despachado'), ('ARCHIVADO', 'Archivado')], default='RECIBIDO', max_length=50, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('tema_filtro', models.CharField(blank=True, choices=[('LAB', 'Laboral'), ('ADM', 'Administrativo'), ('ACA', 'Académico')], max_length=3, null=True)),
                ('institucion', models.CharField(blank=True, max_length=200, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('duracion', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_convenio', models.TextField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('tipo_demanda', models.CharField(blank=True, max_length=150, null=True)),
                ('hora_procedimiento', models.TimeField(blank=True, null=True)),
                ('lugar_procedimiento', models.CharField(blank=True, max_length=255, null=True)),
                ('fase_actual', models.CharField(blank=True, choices=[('INICIO', 'Auto de Inicio'), ('PRUEBAS', 'Periodo Probatorio'), ('CONCL', 'Conclusiones / Dictamen')], max_length=7, null=True)),
                ('cronometro_limite', models.DateTimeField(blank=True, null=True)),
                ('documentos_procesados', models.IntegerField(default=0)),
                ('correspondencia_recibida', models.IntegerField(default=0)),
                ('correspondencia_enviada', models.IntegerField(default=0)),
                ('is_archivado', models.BooleanField(db_column='is_archivado', default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'expedientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LitigioContraparte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_abogado', models.CharField(max_length=150)),
                ('datos_contacto', models.TextField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'litigios_contrapartes',
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tipo', models.TextField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'motivos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('tipo_alerta', models.CharField(max_length=50)),
                ('leido', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PersonaCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('es_cargo_actual', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'persona_cargo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_expediente', models.CharField(blank=True, max_length=50, null=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Personal',
                'db_table': 'personal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SustanciacionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('firma_digital_path', models.CharField(blank=True, max_length=255, null=True)),
                ('huella_digital_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sustanciacion_notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('tipo', models.CharField(choices=[('CONT', 'Contencioso'), ('INSP', 'Inspectoría del Trabajo'), ('OTRO', 'Otros')], max_length=4)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tribunales',
                'db_table': 'tribunales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Actuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(blank=True, db_column='documento_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='documentos.documento')),
            ],
            options={
                'db_table': 'actuaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
