# Generated by Django 5.2.15 on 2026-06-30 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actuacion',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='cargo',
            unique_together={('categoria', 'tipo')},
        ),
        migrations.AddField(
            model_name='expediente',
            name='cargo',
            field=models.ForeignKey(blank=True, db_column='cargo_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='expedientes.cargo'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audienciaagenda',
            name='expediente',
            field=models.ForeignKey(db_column='expediente_id', on_delete=django.db.models.deletion.PROTECT, to='expedientes.expediente'),
        ),
        migrations.AddField(
            model_name='actuacion',
            name='expediente',
            field=models.ForeignKey(db_column='expediente_id', on_delete=django.db.models.deletion.PROTECT, to='expedientes.expediente'),
        ),
        migrations.AddField(
            model_name='litigiocontraparte',
            name='expediente',
            field=models.ForeignKey(db_column='expediente_id', on_delete=django.db.models.deletion.PROTECT, to='expedientes.expediente'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='motivo',
            field=models.ForeignKey(blank=True, db_column='motivo_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='expedientes.motivo'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personacargo',
            name='cargo',
            field=models.ForeignKey(db_column='cargo_id', on_delete=django.db.models.deletion.PROTECT, to='expedientes.cargo'),
        ),
        migrations.AddField(
            model_name='personacargo',
            name='personal',
            field=models.ForeignKey(db_column='personal_id', on_delete=django.db.models.deletion.PROTECT, to='expedientes.personal'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='personal',
            field=models.ForeignKey(blank=True, db_column='personal_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='expedientes.personal'),
        ),
        migrations.AddField(
            model_name='sustanciacionnotificacion',
            name='expediente',
            field=models.ForeignKey(db_column='expediente_id', on_delete=django.db.models.deletion.PROTECT, to='expedientes.expediente'),
        ),
        migrations.AddField(
            model_name='sustanciacionnotificacion',
            name='personal',
            field=models.ForeignKey(db_column='personal_id', on_delete=django.db.models.deletion.PROTECT, to='expedientes.personal'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='tribunal',
            field=models.ForeignKey(blank=True, db_column='tribunal_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='expedientes.tribunal'),
        ),
    ]
