# Generated by Django 5.2.15 on 2026-06-30 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0005_alter_expediente_tipo_demanda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='modulo',
            field=models.ForeignKey(db_column='modulo_id', on_delete=django.db.models.deletion.PROTECT, to='expedientes.modulo'),
        ),
    ]
