# Generated by Django 5.2.15 on 2026-06-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0006_make_modulo_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['categoria']},
        ),
        migrations.AlterUniqueTogether(
            name='cargo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='audienciaagenda',
            name='tipo_evento',
            field=models.TextField(choices=[('AUD', 'Audiencia Judicial'), ('LAPS', 'Lapso Procesal'), ('VENC', 'Vencimiento Contrato'), ('REC', 'Recordatorio General')]),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='tipo',
            field=models.TextField(choices=[('FIJ', 'Fijo / Carrera'), ('CON', 'Contratado'), ('CAR', 'Libre Nombramiento y Remoción')]),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fase_actual',
            field=models.TextField(blank=True, choices=[('INICIO', 'Auto de Inicio'), ('PRUEBAS', 'Periodo Probatorio'), ('CONCL', 'Conclusiones / Dictamen')], null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='modulo',
            field=models.TextField(choices=[('DESP', 'Calificación de Despido / Recientes'), ('INSP', 'Casos de Inspectoría / Horas Extra / Reclamos'), ('OFIC', 'Expedientes en Oficina Consultoría Jurídica'), ('CONT', 'Contrataciones y Convenios de la Universidad'), ('LITI', 'Litigios Judiciales y Administrativos'), ('SUST', 'Sustanciación de Procedimientos Disciplinarios'), ('IND', 'Índices de Inspectoría del Trabajo')]),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tema_filtro',
            field=models.TextField(blank=True, choices=[('LAB', 'Laboral'), ('ADM', 'Administrativo'), ('ACA', 'Académico')], null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo_alerta',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='tipo',
            field=models.TextField(choices=[('CONT', 'Contencioso'), ('INSP', 'Inspectoría del Trabajo'), ('OTRO', 'Otros')]),
        ),
    ]
