# Generated by Django 5.2.15 on 2026-06-30 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alter_modulobiblioteca_modulo'),
        ('expedientes', '0007_alter_cargo_options_alter_cargo_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modulo',
        ),
        migrations.RenameField(
            model_name='expediente',
            old_name='modulo',
            new_name='tipo_modulo',
        ),
    ]
