# Generated by Django 5.2.15 on 2026-06-30 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0008_delete_modulo_rename_modulo_expediente_tipo_modulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='nombre_apellido',
        ),
        migrations.AlterField(
            model_name='expediente',
            name='personal',
            field=models.ForeignKey(db_column='personal_id', on_delete=django.db.models.deletion.PROTECT, to='expedientes.personal'),
            preserve_default=False,
        ),
    ]
