# Generated by Django 5.2.15 on 2026-07-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0009_remove_expediente_nombre_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sustanciacionnotificacion',
            name='firma_digital_path',
        ),
        migrations.AddField(
            model_name='sustanciacionnotificacion',
            name='firma_digital_hash',
            field=models.CharField(blank=True, help_text='Hash SHA-256 de la notificación registrada.', max_length=255, null=True, verbose_name='Firma Digital (SHA-256)'),
        ),
    ]
