# Generated by Django 5.2.15 on 2026-07-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0010_remove_sustanciacionnotificacion_firma_digital_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='firma_digital_hash',
            field=models.CharField(blank=True, help_text='Hash SHA-256 que certifica la notificación.', max_length=255, null=True, verbose_name='Firma Digital (SHA-256)'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='huella_digital_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Huella Digital (SHA-256)'),
        ),
    ]
