# Generated by Django 5.2.15 on 2026-07-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0011_expediente_firma_digital_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='fecha_demanda',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Demanda'),
        ),
    ]
