# Generated by Django 5.2.15 on 2026-07-01 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0012_expediente_fecha_demanda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audienciaagenda',
            name='alerta_email',
            field=models.BooleanField(default=True, verbose_name='Notificar por correo'),
        ),
        migrations.AddField(
            model_name='audienciaagenda',
            name='alerta_sms',
            field=models.BooleanField(default=False, verbose_name='Notificar por SMS'),
        ),
        migrations.AddField(
            model_name='audienciaagenda',
            name='lugar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audienciaagenda',
            name='notificado_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audienciaagenda',
            name='notificado_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audienciaagenda',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Abogado asignado'),
        ),
    ]
