# Generated by Django 5.2.15 on 2026-07-01 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0013_audienciaagenda_alerta_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SujetoProcesal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEF', 'Defensor'), ('FIS', 'Fiscal de Control'), ('JUE', 'Juez de la Causa'), ('SEC', 'Secretario Judicial'), ('CON', 'Contraparte')], max_length=3, verbose_name='Tipo')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(blank=True, max_length=150, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tribunal', models.ForeignKey(blank=True, db_column='tribunal_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='expedientes.tribunal', verbose_name='Tribunal asociado')),
            ],
            options={
                'verbose_name': 'Sujeto Procesal',
                'verbose_name_plural': 'Sujetos Procesales',
                'db_table': 'sujetos_procesales',
                'ordering': ['tipo', 'apellidos', 'nombres'],
            },
        ),
        migrations.AddField(
            model_name='expediente',
            name='defensor',
            field=models.ForeignKey(blank=True, db_column='defensor_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_defensor', to='expedientes.sujetoprocesal', verbose_name='Defensor'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fiscal',
            field=models.ForeignKey(blank=True, db_column='fiscal_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_fiscal', to='expedientes.sujetoprocesal', verbose_name='Fiscal de Control'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='juez',
            field=models.ForeignKey(blank=True, db_column='juez_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_juez', to='expedientes.sujetoprocesal', verbose_name='Juez de la Causa'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='secretario',
            field=models.ForeignKey(blank=True, db_column='secretario_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_secretario', to='expedientes.sujetoprocesal', verbose_name='Secretario Judicial'),
        ),
    ]
