# Generated by Django 5.2.15 on 2026-07-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0014_sujetoprocesal_expediente_defensor_expediente_fiscal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujetoprocesal',
            name='tribunal',
            field=models.TextField(blank=True, choices=[('CONT', 'Contencioso'), ('INSP', 'Inspectoría del Trabajo'), ('OTRO', 'Otros')], null=True, verbose_name='Tribunal asociado'),
        ),
    ]
