# Generated by Django 5.2.15 on 2026-07-01 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0015_alter_sujetoprocesal_tribunal'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='cargo',
            field=models.ForeignKey(blank=True, db_column='cargo_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='expedientes.cargo'),
        ),
    ]
