# Generated by Django 5.2.15 on 2026-07-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0016_add_cargo_to_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='litigiocontraparte',
            name='es_abogado',
            field=models.BooleanField(default=True, verbose_name='Es abogado'),
        ),
    ]
