# Generated by Django 5.2.15 on 2026-07-07 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('expedientes', '0017_litigiocontraparte_es_abogado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actuacion',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='actuacion',
            name='expediente',
        ),
        migrations.AddField(
            model_name='actuacion',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='actuacion',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
