# Generated by Django 5.2.15 on 2026-08-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0018_remove_actuacion_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuacion',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Editar'), ('DELETE', 'Eliminar'), ('ARCHIVE', 'Archivar'), ('UNARCHIVE', 'Desarchivar'), ('NOTIF', 'Notificación')], default='CREATE', max_length=15),
        ),
    ]
