# Generated by Django 5.2.15 on 2026-08-11 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0019_actuacion_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='personal',
            field=models.ForeignKey(blank=True, db_column='personal_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='expedientes.personal'),
        ),
    ]
