# Generated by Django 5.2.15 on 2026-06-30 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('ABOG', 'Abogado'), ('USR_PUBLICO', 'Usuario Público')], default='USR_PUBLICO', max_length=12)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('totp_secret', models.CharField(blank=True, max_length=64, null=True)),
                ('is_2fa_enabled', models.BooleanField(default=False)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('is_bloqueado', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actuacion', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('modulo', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('hash_integridad', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bitacora_auditoria',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialContrasena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='historial_contrasenas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historial_contrasenas',
                'ordering': ['-created_at'],
            },
        ),
    ]
