# Generated by Django 5.2.15 on 2026-06-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraauditoria',
            name='fecha_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacoraauditoria',
            name='registro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacoraauditoria',
            name='tipo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
