# Generated by Django 5.2.15 on 2026-06-30 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0007_alter_cargo_options_alter_cargo_unique_together_and_more'),
        ('usuarios', '0002_bitacoraauditoria_fecha_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='personal',
            field=models.ForeignKey(blank=True, db_column='personal_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='expedientes.personal'),
        ),
    ]
