# Generated by Django 5.2.15 on 2026-06-30 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0009_remove_expediente_nombre_apellido_and_more'),
        ('usuarios', '0003_usuario_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombres',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='personal',
            field=models.ForeignKey(db_column='personal_id', on_delete=django.db.models.deletion.PROTECT, to='expedientes.personal'),
            preserve_default=False,
        ),
    ]
