# Generated by Django 5.2.15 on 2026-07-01 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0013_audienciaagenda_alerta_email_and_more'),
        ('usuarios', '0004_remove_usuario_apellidos_remove_usuario_nombres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='personal',
            field=models.ForeignKey(blank=True, db_column='personal_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='expedientes.personal'),
        ),
    ]
