# Generated by Django 5.2.15 on 2026-07-01 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_personal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitacoraauditoria',
            old_name='actuacion',
            new_name='accion',
        ),
    ]
