# Generated by Django 5.2.15 on 2026-07-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_rename_actuacion_to_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='frase_seguridad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
