# Generated by Django 5.2.15 on 2026-08-20 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0021_cargo_usuario_motivo_usuario_personal_usuario_and_more'),
        ('usuarios', '0008_securityquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='personal',
            field=models.ForeignKey(blank=True, db_column='personal_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_asociado', to='expedientes.personal'),
        ),
    ]
