# Generated by Django 5.2.15 on 2026-08-22 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_usuario_apellidos_usuario_nombres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='personal',
        ),
    ]
