# Generated by Django 5.2.15 on 2026-08-22 21:59

from django.db import migrations

def link_usuarios_personal(apps, schema_editor):
    Usuario = apps.get_model('usuarios', 'Usuario')
    Personal = apps.get_model('expedientes', 'Personal')
    for usuario in Usuario.objects.all():
        personal = Personal.objects.filter(cedula=usuario.cedula).first()
        if personal:
            usuario.personal = personal
            usuario.save()

class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_usuario_personal'),
    ]

    operations = [
        migrations.RunPython(link_usuarios_personal),
    ]
