# Generated by Django 5.2.15 on 2026-08-22 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_link_usuarios_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='personal',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
    ]
