# Generated by Django 5.2.15 on 2026-08-22 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0021_cargo_usuario_motivo_usuario_personal_usuario_and_more'),
        ('usuarios', '0014_remove_usuario_apellidos_remove_usuario_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='personal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_cuenta', to='expedientes.personal'),
        ),
    ]
