# Generated by Django 5.2.15 on 2026-06-30 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoFirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_firma', models.CharField(max_length=64)),
                ('sello_digital_path', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_firma', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documentos_firmas',
            },
        ),
        migrations.CreateModel(
            name='PlantillaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo_plantilla', models.FileField(help_text='Archivo .docx con placeholders {{variable}}', upload_to='plantillas/')),
                ('tipo_salida', models.CharField(choices=[('DOCX', 'Word (.docx)'), ('PDF', 'PDF')], default='DOCX', max_length=4)),
                ('variables', models.JSONField(blank=True, default=list, help_text='Lista de variables disponibles: [{"nombre": "var1", "etiqueta": "Var 1", "tipo": "text"}]')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plantillas_documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_original', models.CharField(max_length=255)),
                ('nombre_cifrado', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(max_length=100)),
                ('hash_sha256', models.CharField(max_length=64)),
                ('iv_cifrado', models.CharField(max_length=512)),
                ('qr_code_content', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('contenido_ocr', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('es_plantilla', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('biblioteca', models.ForeignKey(blank=True, db_column='biblioteca_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='biblioteca.modulobiblioteca')),
            ],
            options={
                'db_table': 'documentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
