# Generated by Django 5.2.15 on 2026-06-30 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biblioteca', '0001_initial'),
        ('documentos', '0001_initial'),
        ('expedientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='expediente',
            field=models.ForeignKey(blank=True, db_column='expediente_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='expedientes.expediente'),
        ),
        migrations.AddField(
            model_name='documento',
            name='normativa_citada',
            field=models.ForeignKey(blank=True, db_column='normativa_citada_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citado_en_documentos', to='biblioteca.modulobiblioteca'),
        ),
        migrations.AddField(
            model_name='documento',
            name='parent_documento',
            field=models.ForeignKey(blank=True, db_column='parent_documento_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='documentos.documento'),
        ),
        migrations.AddField(
            model_name='documentofirma',
            name='documento',
            field=models.ForeignKey(db_column='documento_id', on_delete=django.db.models.deletion.PROTECT, to='documentos.documento'),
        ),
        migrations.AddField(
            model_name='documentofirma',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantilladocumento',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='documentofirma',
            unique_together={('documento', 'usuario')},
        ),
    ]
