# Generated by Django 5.2.15 on 2026-06-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilladocumento',
            name='tipo_salida',
            field=models.TextField(choices=[('DOCX', 'Word (.docx)'), ('PDF', 'PDF')], default='DOCX'),
        ),
    ]
