# Generated by Django 5.2.15 on 2026-06-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_alter_plantilladocumento_tipo_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo_mime',
            field=models.TextField(),
        ),
    ]
