# Generated by Django 5.2.15 on 2026-07-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_documentoversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='contenido_ocr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
