# Generated by Django 5.2.15 on 2026-07-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_documentoversion'),
    ]

    operations = [
    ]
