# Generated by Django 5.2.15 on 2026-07-09 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_add_contenido_ocr_field'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE documentos ADD FULLTEXT INDEX idx_fulltext_doc (nombre_original, contenido_ocr);",
            reverse_sql="ALTER TABLE documentos DROP INDEX idx_fulltext_doc;"
        ),
    ]
