# Generated by Django 5.2.15 on 2026-08-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_add_fulltext_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='qr_code_content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
