# Generated by Django 5.2.15 on 2026-06-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloBiblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo_normativa', models.CharField(choices=[('REGL', 'Reglamento Interno'), ('RESCU', 'Resolución de Consejo Universitario'), ('GAC', 'Gaceta Oficial')], max_length=5)),
                ('fecha_publicacion', models.DateField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'modulo_biblioteca',
                'ordering': ['-created_at'],
            },
        ),
    ]
