# Generated by Django 5.2.15 on 2026-06-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulobiblioteca',
            name='tipo_normativa',
            field=models.TextField(choices=[('REGL', 'Reglamento Interno'), ('RESCU', 'Resolución de Consejo Universitario'), ('GAC', 'Gaceta Oficial')]),
        ),
    ]
