# Generated by Django 5.2.15 on 2026-06-30 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_modulobiblioteca_tipo_normativa'),
        ('expedientes', '0004_modulo_remove_expediente_tipo_modulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulobiblioteca',
            name='modulo',
            field=models.ForeignKey(blank=True, db_column='modulo_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='expedientes.modulo'),
        ),
    ]
