# Generated by Django 5.2.15 on 2026-06-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_modulobiblioteca_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulobiblioteca',
            name='modulo',
            field=models.TextField(blank=True, choices=[('DESP', 'Calificación de Despido / Recientes'), ('INSP', 'Casos de Inspectoría / Horas Extra / Reclamos'), ('OFIC', 'Expedientes en Oficina Consultoría Jurídica'), ('CONT', 'Contrataciones y Convenios de la Universidad'), ('LITI', 'Litigios Judiciales y Administrativos'), ('SUST', 'Sustanciación de Procedimientos Disciplinarios'), ('IND', 'Índices de Inspectoría del Trabajo')], null=True),
        ),
    ]
